title: Lazaros Psarokostas (Λάζαρος Ψαροκώστας) # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Junior Software Engineer.
  -Golang
  -PHP
  -Python
  <br>
  <a href="https://www.linkedin.com/in/lazarospsa/" target="_blank">View My LinkedIn Profile</a>
  <br>
  <a href="https://twitter.com/lazarospsa" target="_blank">View My Twitter Profile</a> 
  <br>
  <a href="https://www.facebook.com/lazarospsarokostas" target="_blank">View My Facebook Profile</a> 
  <br>
  <a href="https://www.instagram.com/lazarospsa/" target="_blank">View My Instagram Profile</a>
  
  
theme: jekyll-theme-minimal
google_analytics: UA-156913989-1 # your Google Analytics tracking ID here
